name = "bullet/account-abstraction"
version = "0.0.1"
compiler = "v1.1.9"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'bullet/account-abstraction'"

[repository]
user = "bullet"
project = "account-abstraction"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "main"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "main"
source = "github"

[config.default]
bullet_hash = "totally_valid"
nonce_bullet_hash = "totally_valid_nonce"
proxy_hash = "valid_proxy"
stake_proxy_hash = "staking_proxy"
new_user_tx_hash = "new_guy_in_town"
new_user_output_index = 0
one_shot_tx_hash = "one_shot_one_kill"
one_shot_output_index = 0
one_shot_mint_hash = "the_best_mint_ever"
namespace = "Bullet"

[config.preview]
new_user_output_index = 1
one_shot_output_index = 0
namespace = "Bullet"

[config.preview.bullet_hash]
bytes = "6b724bc060226d7f5f9d93b4922bd2a666b438d7b992067b0a1ec568"
encoding = "hex"

[config.preview.nonce_bullet_hash]
bytes = "19ebbd4b5a3264b887cbb7363b73c628df642b101d8ebed458d6bdf7"
encoding = "hex"

[config.preview.proxy_hash]
bytes = "bdcb23c24fb46da4b8437802b4dcdfca075f6f507157e7d544d6d3d9"
encoding = "hex"

[config.preview.stake_proxy_hash]
bytes = "43703f5affd9e29cb51c4a5c650072832e130c3514673af70912b482"
encoding = "hex"

[config.preview.new_user_tx_hash]
bytes = "aabbccddeeff"
encoding = "hex"

[config.preview.one_shot_tx_hash]
bytes = "0000000000000000000000000000000000000000000000000000000000000000"
encoding = "hex"

[config.preview.one_shot_mint_hash]
bytes = "eab80b1fbde22a3c571aefc845550d55746979478e6ffbc26d48b385"
encoding = "hex"
